config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do  
     get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  root 'facilities#index'
  resources :facilities, only: [:index, :show]
  resources :bookings, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :facility

  validate :no_double_booking

  private

  def no_double_booking
    existing_bookings = Booking.where(facility_id: facility_id).where.not(id: id)
  
    existing_bookings.each do |existing_booking|
      if overlaps?(existing_booking)
        errors.add(:booking_time, 'overlaps with another booking')
        break
      end
    end
  end
  

  def overlaps?(existing_booking)
    return false unless duration.present? && existing_booking.duration.present?
    new_booking_start = booking_time
    new_booking_end = booking_time + (duration || 0).hours
  
    existing_booking_start = existing_booking.booking_time
    existing_booking_end = existing_booking.booking_time + (existing_booking.duration || 0).hours
  
    new_booking_start < existing_booking_end && new_booking_end > existing_booking_start
  end 
  
end

app/models/facility.rb
class Facility < ApplicationRecord
    has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user! # Ensures that users are logged in to access certain actions

    def after_sign_out_path_for(resource_or_scope)
        root_path # Redirect to the root path after logout
    end

    # Customize the path after sign up
    def after_sign_up_path_for(resource_or_scope)
        root_path # Redirect to the root path after sign up
    end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def create
    @booking = current_user.bookings.build(booking_params)


  Rails.logger.debug "Booking Params: #{booking_params.inspect}"
  Rails.logger.debug "Booking Details: #{@booking.inspect}"
  
    if @booking.save
      redirect_to facility_path(@booking.facility), notice: 'Booking was successful.'
    else
      redirect_to facility_path(@booking.facility), alert: 'Booking failed. This slot might already be booked.'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:facility_id, :booking_time, :duration)
  end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  def index
    @facilities = Facility.all
    @facilities = @facilities.where("sports_name LIKE ?", "%#{params[:sports_name]}%") if params[:sports_name].present?
    @facilities = @facilities.where("pincode = ?", params[:pincode]) if params[:pincode].present?
  end

  def show
    @facility = Facility.find(params[:id])
    @bookings = @facility.bookings.order(:booking_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/facilities/index.html.erb
<h1>Available Sports Facilities</h1>

<%= form_with url: facilities_path, method: :get, local: true do %>
  <div>
    <%= label_tag :sports_name, "Filter by Sports Name" %>
    <%= text_field_tag :sports_name, params[:sports_name] %>
  </div>
  <div>
    <%= label_tag :pincode, "Filter by Pincode" %>
    <%= text_field_tag :pincode, params[:pincode] %>
  </div>
  <%= submit_tag "Search" %>
<% end %>

<ul>
  <% @facilities.each do |facility| %>
    <li>
      <h2><%= link_to facility.name, facility_path(facility) %></h2>
      <p><%= facility.description %></p>
      <p>Location: <%= facility.location %> (Pincode: <%= facility.pincode %>)</p>
    </li>
  <% end %>
</ul>

app/views/facilities/show.html.erb
<h1><%= @facility.name %></h1>
<p><%= @facility.description %></p>
<p>Location: <%= @facility.location %></p>

<h3>Book This Facility</h3>
<ul>
  <% @bookings.each_with_index do |booking, index| %>
    <li>
      Booked from <%= booking.booking_time.strftime("%H:%M") %> to <%= (booking.booking_time + (booking.duration || 0).hours).strftime("%H:%M") %>
      
      <% if index < @bookings.size - 1 %>
        <% next_booking = @bookings[index + 1] %>
        <% if next_booking.booking_time > (booking.booking_time + (booking.duration || 0).hours) %>
          <p>Available from <%= (booking.booking_time + (booking.duration || 0).hours).strftime("%H:%M") %> to <%= next_booking.booking_time.strftime("%H:%M") %></p>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= form_with model: Booking.new, url: bookings_path, local: true do |f| %>
  <%= f.hidden_field :facility_id, value: @facility.id %>
  <div>
    <%= f.label :booking_time, "Booking Time" %>
    <%= f.datetime_select :booking_time %>
  </div>
  <div>
    <%= f.label :duration, "Duration (in hours)" %>
    <%= f.number_field :duration, value: 1 %> <!-- Added a default value of 1 hour -->
  </div>
  <%= f.submit "Book Now" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportsFacilityBookingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </head>

  <body>
  <% if user_signed_in? %>
  <p>Welcome, <%= current_user.email %>!</p>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  <% else %>
  <% end %>
    <%= yield %>
  </body>
</html>